network:
        version: 2
        renderer: networkd
        ethernets: 
           wlp3s0:
                dhcp4: true
           enx00e04c000da8:
                dhcp4: true
           enx00e04c002ab0:
                dhcp4: true
                addresses: [192.168.3.2/30]
           enp0s25:
                dhcp4: true
